services:

  app:
    image: registry.in.psu.ac.th:443/6610210454/adt-frontend

    container_name: client-adaptive-learning

    ports:
      - "5173:80"

    environment:
      NODE_ENV: development

        


